name: Delivery
on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      DEPLOY_DIRECTORY: /usr/local/src/apps/discord-purger-chat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          sudo apt-get install ssh
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh ${{ secrets.HOST }} -i deploy_key.pem "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ secrets.HOST }}{{ secrets.IP_ADDRESS }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Show info
        run: |
          ssh {{ env.HOST }} -i deploy_key.pem "cd ${{ env.DEPLOY_DIRECTORY }} && ls"